"""
Content Data Models
Defines models for content blocks, templates, and generated pages.
"""

from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any, Callable
from enum import Enum
from datetime import datetime


class ContentType(Enum):
    """Types of content that can be generated."""
    FAQ = "faq"
    PRODUCT_PAGE = "product_page"
    COMPARISON = "comparison"
    DESCRIPTION = "description"


@dataclass
class ContentBlock:
    """
    Represents a reusable content block generated by a logic block.
    This is the output of content transformation functions.
    """
    block_type: str
    content: Dict[str, Any]
    metadata: Dict[str, Any] = field(default_factory=dict)
    dependencies: List[str] = field(default_factory=list)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "block_type": self.block_type,
            "content": self.content,
            "metadata": self.metadata,
            "dependencies": self.dependencies
        }


@dataclass
class TemplateField:
    """Definition of a field within a template."""
    name: str
    field_type: str  # text, list, object, number
    required: bool = True
    default: Any = None
    source_block: Optional[str] = None  # Which content block provides this
    transform: Optional[str] = None  # Transformation rule to apply


@dataclass
class PageTemplate:
    """
    Template definition for a page type.
    Specifies the structure, fields, and rules for generating a page.
    """
    template_id: str
    template_name: str
    content_type: ContentType
    fields: List[TemplateField] = field(default_factory=list)
    required_blocks: List[str] = field(default_factory=list)
    formatting_rules: Dict[str, Any] = field(default_factory=dict)
    
    def get_field(self, field_name: str) -> Optional[TemplateField]:
        """Get a field by name."""
        for f in self.fields:
            if f.name == field_name:
                return f
        return None
    
    def validate_blocks(self, available_blocks: List[str]) -> bool:
        """Check if all required blocks are available."""
        return all(block in available_blocks for block in self.required_blocks)


@dataclass
class GeneratedPage:
    """
    A fully generated page ready for output.
    This is the final output of the content generation pipeline.
    """
    page_type: ContentType
    title: str
    content: Dict[str, Any]
    metadata: Dict[str, Any] = field(default_factory=dict)
    generated_at: str = field(default_factory=lambda: datetime.now().isoformat())
    template_used: Optional[str] = None
    blocks_used: List[str] = field(default_factory=list)
    
    def to_json(self) -> Dict[str, Any]:
        """Convert to JSON-serializable dictionary."""
        return {
            "page_type": self.page_type.value,
            "title": self.title,
            "content": self.content,
            "metadata": {
                **self.metadata,
                "generated_at": self.generated_at,
                "template_used": self.template_used,
                "blocks_used": self.blocks_used
            }
        }
